language: node_js
install:
 - npm install -g codecov
 - npm install
script:
 - npm test
 - codecov
after_success:
 - bash <(curl -s https://codecov.io/bash)
 - bash .travis_deploy.sh
node_js:
 - 6.1.0
env:
  global:
      - secure: "Wk0zk7uYHE7UaWGKdRY4sDRNgTWXLb3Pt8OkLUp4okV7b5m/MowOOjWpw08vTRhtDT0RqkU+b60DVasGj0hj35TlAhs/te/S9e8cQsYfSIRbUmt9UoGpBP1QZfdOuqfsPIbOVPXdlVxRQztsUvECDxktRQixuXf9J+WBLaBPNaPtXXhrq9ijptJCJriVfJ1XMtKaS/WRgfhGwItsDlueeG3GwBfuorditEltOE5tK2RUfDLOBJZtcnjMWx4sxCBflzrPokRhdTIJiec3Yrczns36Vm7XK2RolhokQMeLAsFm+nuN7hC7Z0qhW6KvLLoik4BaAMpto7ldJPBlAMilLJdOAwKALB2hXS5CnjkKxgthWjZqBRuX526EdxvUyUztzuwe3mDNuU7l0VJ1Cx6J+kxYX2baReerB9iwXDvT1RM9ZPS1Mfrzmt0iPxc0zj7C1MXR2aes86CIAt7JebsRHDDuUaDcM6Bou3Ighbvd6J8aGqLvLlZGC1+/80Y0vfjTZNihoHH3jV1yI+EWjKf4dQA6W6jL6X4M50awMjyM4Jsun+nAXWCsiNthXXcPgq1rJ/I6R9wKEvZ7/0dapmexVVt/gOLHxdIO5SBTcKVcQjTCVzeavXFizIOiJhxohlrxhv0ExY9MX6jQWW6qsUVCHFNWkpqCeWADHs+T0ZbdWE0="
