services:
- mongodb
addons:
  code_climate:
    repo_token: 2cd26ede3ca1d6
language: node_js
script: npm test
after_script:
- codeclimate-test-reporter < ./build/coverage/report-lcov/lcov.info
after_success:
node_js:
- 6.1.0
env:
  global:
